import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { type ReactNode } from "react";
import { Header } from "@/widgets/header/ui/header";
import { auth } from "@/server/auth";
import { headers } from "next/headers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin", "cyrillic"],
  variable: "--font-sans",
});

interface RootLayoutProps {
  children: ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  const session = await auth.api.getSession({
    headers: await headers(),
  });

  return (
    <html lang="en" className={`${inter.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header
          name={session?.user.name ?? ""}
          email={session?.user.email ?? ""}
          avatar={session?.user.image ?? ""}
        />
        {children}
      </body>
    </html>
  );
}
